version: '3.7'
services:
  db:
    container_name: postgres
    image: postgres:15.5
    environment:
      POSTGRES_USER: somu
      POSTGRES_PASSWORD: password
      PGDATA: /var/lib/postgresql/data  # Corrected path
    volumes:
      - ./data:/var/lib/postgresql/data  # Use a relative path
    ports:
      - "5332:5432"
    networks:
      - db
    restart: unless-stopped

  somu-api:
    container_name: somu-api
    image: somusaxena20/somu-api
    environment:
      SPRING_DATASOURCE_URL: "jdbc:postgresql:// :5432/somuuat"
    ports:
      - "1000:1000"
    networks:
      - db
    depends_on:
      - db
    restart: unless-stopped

networks:
  db:
    driver: bridge

volumes:
  db: