spring:
  datasource:
    url: jdbc:postgresql://localhost:5332/somuuat
    username: somu
    password: password
  jpa:
    hibernate:
      ddl-auto: none
    #      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    show-sql: true
  codec:
    max-in-memory-size: 5000KB
