spring:
  datasource:
    url: jdbc:postgresql://localhost:5332/somuprod
    username: somu
    password: password
  jpa:
    hibernate:
      ddl-auto: validate
#      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    show-sql: true
