server:
  error:
    include-message: always
spring:
  profiles:
    active: uat
#  datasource:
#    url: jdbc:postgresql://localhost:5332/somuuat
#    username: somu
#    password: password
#  jpa:
#    hibernate:
#      ddl-auto: none
#    properties:
#      hibernate:
#        format_sql: true
#    show-sql: true